version: '3.8'

services:
  web:
    image: php:apache
    ports:
      - "80:80"
    volumes:
      - .:/var/www/html
    env_file:
      - .env
    depends_on:
      - mariadb
  mariadb:
    image: mariadb:10.11
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
      - mariadb_data:/var/lib/mysql
      - ./docker/initdb:/docker-entrypoint-initdb.d
  composer:
    image: composer
    command: install
    volumes:
      - .:/var/www/html
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8080:80"
    environment:
      PMA_HOST: mariadb
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    depends_on:
      - mariadb

volumes:
  mariadb_data:
